/*
*Kareem Al Tulaihi
*Java Project
*/
package laad;

/**
 *
 * @author Kareem
 */
public class Eyes extends javax.swing.JPanel {

    /**
     * Creates new form Brain
     */
    public Eyes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laad/eye.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 20, 150, 150);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("electrical signals, and transmits these signals to the brain through complex neural pathways that ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 260, 470, 10);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Eyes are the organs of vision. They detect light and convert it into electro-chemical impulses ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 180, 470, 20);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" in neurons. In higher organisms, the eye is a complex optical system which collects light from the");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 200, 470, 14);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" it through an adjustable assembly of lenses to form an image, converts this image into a set of");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 240, 470, 14);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("surrounding environment, regulates its intensity through a diaphragm, focuses it through an");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 220, 470, 14);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("connect the eye via the optic nerve to the visual cortex and other areas of the brain. Eyes with ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 270, 470, 20);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("and arthropods.");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 330, 460, 20);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" resolving power have come in ten fundamentally different forms, and 96% of animal species ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 290, 500, 20);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("possess a complex optical system.Image-resolving eyes are present in molluscs, chordates");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 310, 460, 20);

        jButton1.setText("Go To Quizz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(190, 370, 110, 50);

        jButton2.setText("Home");
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 510, 59, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laad/bg1.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    BrainQ r = new BrainQ();
    r.setVisible(true);  
    dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
