/*
*Kareem Al Tulaihi
*Java Project
*Section:Brain
*/
package laad;

/**
 *
 * @author Kareem
 */
public class Info extends javax.swing.JPanel {

    /**
     * Creates new form Brain
     */
    public Info() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laad/brain.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 20, 150, 150);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("hearing, balance, taste, and smell.  The brain is the most complex organ in a vertebrate's body. ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 260, 470, 40);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("The brain is an organ that serves as the center of  the nervous system in all vertebrate and most");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 180, 470, 40);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("invertebrate animals—only  a few invertebrates such as sponges, jellyfish, adult sea squirts ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 200, 470, 40);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("located in the head,  usually close to the primary sensory  organs for such senses as vision,");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 240, 470, 40);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("and starfish  do not have a brain; diffuse or localised nerve nets are present instead.The brain is");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 220, 470, 40);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("In a typical human, the cerebral cortex (the largest part) is estimated to  contain 15–33 billion ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 290, 460, 20);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("potentials to distant parts of the  brain or body targeting specific recipient cells.");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 330, 460, 20);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("means of long protoplasmic fibers called axons, which carry trains of signal pulses called action");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 310, 460, 20);

        jButton1.setText("Go To Quizz");
        jPanel1.add(jButton1);
        jButton1.setBounds(190, 370, 110, 50);

        jButton2.setText("Home");
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 520, 59, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/laad/bg1.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
